# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title: Yash Mehrotra
tagline: ''
description: 'Description'
baseurl: ''
paginate: 10
github_repo: http://github.com/yashmehrotra/

# About/contact
author:
  name: Yash Mehrotra
  url: https://twitter.com/yashm95
  email: yashmehrotra95@gmail.com

