# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title: Shivam Singh
tagline: ''
description: 'Description'
baseurl: ''
paginate: 10
github_repo: http://github.com/shivam043/

# About/contact
author:
  name: Shivam Singh
  url: https://twitter.com/2shivamsingh
  email: shivam043@gmail.com

